### ISSUE TITLE
Exception when variable is declared in `for...in` initialization

### ISSUE THREAD

**Issue by mseeley** [avaly/babel-plugin-inline-classnames#4]
👋 @avaly. A bug snuck in on 9eed5bb715b664a57ce86e263ad0e12e5eb0ad9b.

Save the file below to `test/fixtures/{foo}.js`:

```js
import classnames from 'classnames';
import styles from './styles.css';

const object = {};

for (const key in object) {
  classnames(styles.foo, styles.bar);
}
```

Execute `npm test`:

```
    TypeError: Cannot read property 'type' of null

      234 | 					declaration =>
      235 | 						declaration.type === 'VariableDeclarator' &&
    > 236 | 						declaration.init.type === 'CallExpression',
          | 						                 ^
      237 | 				)
      238 | 				.some(declaration => {
      239 | 					if (isCalleeClassnamesBind(declaration.init.callee, scope)) {

      at type (src/index.js:236:24)
          at Array.filter (<anonymous>)
      at PluginPass.filter (src/index.js:233:6)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:193:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:90:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:146:19)
```

`declaration.init === null` in the code above. I'll PR shortly; just wanted a bug to tie the fix to.

**Comment by avaly** [comment]
PR merged and `v1.2.1` (babel v6) and `v2.0.1` (babel v7) published to npm. Thanks @mseeley!
